### ISSUE TITLE
Build fail fast_tests 2319521641

### ISSUE THREAD

**Issue by mongolianjesus** [ParticleDev/p1_data_client#21]
```
FAILED test/test_client_jupyter.py::TestP1EdgarDataClientExampleNotebook::test_notebook1
FAILED test/test_edgar_client.py::TestEdgarClient::test_form10_1_cik_publication_date
FAILED test/test_edgar_client.py::TestEdgarClient::test_form10_multi_cik_publication_date
```'

```
cmd='(cd /home/runner/work/p1_data_client/p1_data_client/test/TestP1EdgarDataClientExampleNotebook.test_notebook1/tmp.scratch &&  jupyter nbconvert /home/runner/work/p1_data_client/p1_data_client/notebooks/p1_edgar_data_client_example.ipynb --execute --to html --ExecutePreprocessor.kernel_name=python --ExecutePreprocessor.timeout=-1) 2>&1' failed with rc='1'
################################################################################
[NbConvertApp] Converting notebook /home/runner/work/p1_data_client/p1_data_client/notebooks/p1_edgar_data_client_example.ipynb to html
[NbConvertApp] Executing notebook with kernel: python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 119, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 369, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Get Form10 data for one CIK and 2 days.
payload = client.get_form10_payload(
    cik=1002910, 
    start_datetime="2020-05-11T00:00:00-00:00", 
    end_datetime="2020-05-13T00:00:00-00:00",
    date_mode="publication_date",
)

MaxRetryError                             Traceback (most recent call last)
/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    858                 body_pos=body_pos,
--> 859                 **response_kw
    860             )

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    858                 body_pos=body_pos,
--> 859                 **response_kw
    860             )

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    858                 body_pos=body_pos,
--> 859                 **response_kw
    860             )

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    858                 body_pos=body_pos,
--> 859                 **response_kw
    860             )

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    858                 body_pos=body_pos,
--> 859                 **response_kw
    860             )

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    835             try:
--> 836                 retries = retries.increment(method, url, response=response, _pool=self)
    837             except MaxRetryError:

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    573         if new_retry.is_exhausted():
--> 574             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    575 

MaxRetryError: HTTPSConnectionPool(host='data.particle.one', port=443): Max retries exceeded with url: /edgar/v7/data/form10?start_datetime=2020-05-11T00%3A00%3A00-00%3A00&end_datetime=2020-05-13T00%3A00%3A00-00%3A00&date_mode=publication_date&cik=1002910 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

RetryError                                Traceback (most recent call last)
<ipython-input-1-f2580d0084a8> in <module>
      4     start_datetime="2020-05-11T00:00:00-00:00",
      5     end_datetime="2020-05-13T00:00:00-00:00",
----> 6     date_mode="publication_date",
      7 )

~/work/p1_data_client/p1_data_client/p1_data_client_python/edgar/edgar_client.py in get_form10_payload(self, cik, start_datetime, end_datetime, date_mode)
    218                 self._set_optional_params(params, cik=current_cik)
    219                 response = self._make_request(
--> 220                     "GET", url, headers=self.headers, params=params
    221                 )
    222                 self.spinner.stop()

~/work/p1_data_client/p1_data_client/p1_data_client_python/abstract_client.py in _make_request(self, *args, **kwargs)
    172             kwargs["headers"] = dict()
    173         kwargs["headers"]["User-Agent"] = self._get_versions()
--> 174         response = self.session.request(*args, **kwargs)
    175         # Throw exception, if token is not valid.
    176         if response.status_code == 401:

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    540         }
    541         send_kwargs.update(settings)
--> 542         resp = self.send(prep, **send_kwargs)
    543 
    544         return resp

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/sessions.py in send(self, request, **kwargs)
    653 
    654         # Send the request
--> 655         r = adapter.send(request, **kwargs)
    656 
    657         # Total elapsed time of the request (approximately)

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    505 
    506             if isinstance(e.reason, ResponseError):
--> 507                 raise RetryError(e, request=request)
    508 
    509             if isinstance(e.reason, _ProxyError):

RetryError: HTTPSConnectionPool(host='data.particle.one', port=443): Max retries exceeded with url: /edgar/v7/data/form10?start_datetime=2020-05-11T00%3A00%3A00-00%3A00&end_datetime=2020-05-13T00%3A00%3A00-00%3A00&date_mode=publication_date&cik=1002910 (Caused by ResponseError('too many 500 error responses'))
RetryError: HTTPSConnectionPool(host='data.particle.one', port=443): Max retries exceeded with url: /edgar/v7/data/form10?start_datetime=2020-05-11T00%3A00%3A00-00%3A00&end_datetime=2020-05-13T00%3A00%3A00-00%3A00&date_mode=publication_date&cik=1002910 (Caused by ResponseError('too many 500 error responses'))

```

Link: https://github.com/ParticleDev/p1_data_client/runs/2319521641?check_suite_focus=true

**Comment by dremdem** [comment]
Fixed restarting Form10 container by @greg-ptcl
